sudo: required
services:
 - docker
before_install:
 - docker build -t fanzoudocker/simpweb -f Dockerfile.dev .
script:
 - docker run -e CI=true fanzoudocker/simpweb npm run test
deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "simpleweb"
 env: "Simpleweb-env"
 bucket_name: "elasticbeanstalk-us-east-2-425848420508"
 bucket_path: "simpleweb"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: "$AWS_SECRET_KEY"
